// <auto-generated />
using System;
using KOI_XS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KOI_XS.DAL.Migrations
{
    [DbContext(typeof(KoiContext))]
    partial class KoiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KOI_XS.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "nguyenvana@example.com",
                            Name = "Nguyen Van A"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "tranthib@example.com",
                            Name = "Tran Thi B"
                        });
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.KoiFish", b =>
                {
                    b.Property<int>("KoiFishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoiFishId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KoiFishId");

                    b.ToTable("KoiFishes");

                    b.HasData(
                        new
                        {
                            KoiFishId = 1,
                            Color = "Red",
                            Name = "Koi Red Dragon",
                            Price = 150.00m
                        },
                        new
                        {
                            KoiFishId = 2,
                            Color = "Black",
                            Name = "Koi Black Beauty",
                            Price = 200.00m
                        },
                        new
                        {
                            KoiFishId = 3,
                            Color = "White",
                            Name = "Koi White Pearl",
                            Price = 180.00m
                        });
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 10, 23, 16, 1, 47, 341, DateTimeKind.Local).AddTicks(4832)
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2024, 10, 28, 16, 1, 47, 341, DateTimeKind.Local).AddTicks(4879)
                        });
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.OrderKoi", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("KoiFishId")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "KoiFishId");

                    b.HasIndex("KoiFishId");

                    b.ToTable("OrderKois");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            KoiFishId = 1
                        },
                        new
                        {
                            OrderId = 1,
                            KoiFishId = 2
                        },
                        new
                        {
                            OrderId = 2,
                            KoiFishId = 3
                        });
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.Order", b =>
                {
                    b.HasOne("KOI_XS.DAL.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.OrderKoi", b =>
                {
                    b.HasOne("KOI_XS.DAL.Entities.KoiFish", "KoiFish")
                        .WithMany("OrderKois")
                        .HasForeignKey("KoiFishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KOI_XS.DAL.Entities.Order", "Order")
                        .WithMany("OrderKois")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KoiFish");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.KoiFish", b =>
                {
                    b.Navigation("OrderKois");
                });

            modelBuilder.Entity("KOI_XS.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderKois");
                });
#pragma warning restore 612, 618
        }
    }
}
